# Generated by Django 4.2.7 on 2023-11-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw15_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='about_me',
            field=models.TextField(default=''),
        ),
    ]
