# Generated by Django 4.2.7 on 2023-11-30 13:06

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def create_profile_for_existing_users(apps, schemas_editors):
    user_model = apps.get_model('auth', 'User')
    profile_model = apps.get_model('hw15_app', 'Profile')

    users = user_model.objects.filter(profile__isnull=True).all()
    # for user in users:
    #     profile = profile_model(user=user)
    #     profile.save()

    profiles = [profile_model(user=user) for user in users]
    profile_model.objects.bulk_create(profiles)


class Migration(migrations.Migration):
    dependencies = [
        ('hw15_app', '0003_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile',
                                              to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_profile_for_existing_users)
    ]
