# Generated by Django 4.2.7 on 2023-12-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw15_app', '0005_profile_about_profile_avatar_profile_social_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(max_length=4096),
        ),
    ]
