# Generated by Django 4.2.8 on 2023-12-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags_app', '0001_initial'),
        ('hw15_app', '0011_alter_postimage_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(related_name='post_tags', to='tags_app.tag'),
        ),
    ]
