# Generated by Django 4.2.8 on 2023-12-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags_app', '0001_initial'),
        ('hw15_app', '0013_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_tags', to='tags_app.tag'),
        ),
    ]
