# Generated by Django 4.2.8 on 2023-12-19 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw15_app', '0014_alter_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
    ]
