# Generated by Django 4.2.8 on 2023-12-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw15_app', '0016_post_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='images',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
