# Generated by Django 4.2.8 on 2023-12-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='url',
            field=models.CharField(max_length=256),
        ),
    ]
