# Generated by Django 4.2.8 on 2023-12-12 13:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_alter_menuitems_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=256)),
                ('priority', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)])),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu_app.menu')),
            ],
        ),
        migrations.DeleteModel(
            name='MenuItems',
        ),
    ]
